Compatibility with Angular 14 (https://github.com/merlosy/ngx-materia…
merlosy/ngx-material-file-input pull request #113
Opened 2022-06-14 10:09 UTC by sharmanikhil04

…l-file-input/issues/111)

-Upgrading dependencies
-Adding stateChanges property to support changes to MatFormFieldControl in v14

2022-06-15 13:42 UTC, jonaskistler approved these changes

2022-06-16 06:50 UTC, rRaDuCaN approved these changes

2022-06-16 08:25 UTC, JeremieLapert commented on libs/material-file-input/src/lib/file-input/file-input.component.ts
> +import {MatFormFieldControl} from "@angular/material/form-field";
a space is missing for your import

2022-06-16 08:25 UTC, JeremieLapert commented on libs/material-file-input/src/lib/file-input/file-input-mixin.ts
> +import {ErrorStateMatcher, mixinErrorState} from '@angular/material/core';
a space is missing for your import

2022-06-16 08:25 UTC, JeremieLapert commented on package.json
> +    "@nrwl/cli": "14.0.1",
We are now in version 14.3.5 for NX cf https://github.com/nrwl/nx/releases/tag/14.3.5

2022-06-16 15:22 UTC, sharmanikhil04 commented on libs/material-file-input/src/lib/file-input/file-input.component.ts
> +import {MatFormFieldControl} from "@angular/material/form-field";
Fix this. Please review

2022-06-17 06:26 UTC, JeremieLapert approved these changes

2022-06-17 06:27 UTC, JeremieLapert approved these changes

2022-06-17 06:28 UTC, JeremieLapert approved these changes

2022-06-17 09:48 UTC, rRaDuCaN approved these changes

2022-06-17 09:51 UTC, rRaDuCaN approved these changes

2022-06-20 06:31 UTC, rRaDuCaN approved these changes

2022-06-20 06:33 UTC, rRaDuCaN requested changes
seems fine, just commented to trigger this darn PR

2022-06-20 07:16 UTC, sharmanikhil04 commented
> seems fine, just commented to trigger this darn PR

Hi @rRaDuCaN , I am also waiting for @merlosy  to approve and merge this PR.

2022-06-20 09:53 UTC, winfa commented
hi @rRaDuCaN, I have already upgrade my project to angular 14, but found this issue before release. Could this issue been resolved ASAP? Or I may have to revert my code to angular 13...

2022-06-20 11:39 UTC, rRaDuCaN commented
@sharmanikhil04 , I guess @merlosy doesn't use this account anymore, at least I don't see any activity from him. Also, it's pretty annoying that angular material doesn't provide a built in for files, the same problem with datepicker (problem solved in material ui for react to bring it up)

2022-06-21 02:38 UTC, winfa commented
Hi @sharmanikhil04, I was trying to build based on your PR but found errors when run `npm run build` or `npm run build:lib`. Maybe the angular upgrade part may should be covered by nx.

Also, not sure if it is possible to keep the dependency as angular 13, and just update the code and keep stateChanges as optional to make this lib support angular 13 and angular 14. 

@rRaDuCaN  @sharmanikhil04 
And btw, if @merlosy does not use this account anymore. Do we have any other plans? Do we have any other person can contact with? Or maybe publish this change to anther place?

2022-06-21 04:17 UTC, sharmanikhil04 commented
> Hi @sharmanikhil04, I was trying to build based on your PR but found errors when run `npm run build` or `npm run build:lib`. Maybe the angular upgrade part may should be covered by nx.
> 
> Also, not sure if it is possible to keep the dependency as angular 13, and just update the code and keep stateChanges as optional to make this lib support angular 13 and angular 14.
> 
> @rRaDuCaN @sharmanikhil04 And btw, if @merlosy does not use this account anymore. Do we have any other plans? Do we have any other person can contact with? Or maybe publish this change to anther place?

@winfa  I had upgraded Angular version first to  simulate the error and then added stateChanges . Not sure if we should  stateChanges as Optional without Angular upgrade.
Anyhow, I can see  @mcaden  and @matcho have also committed to this library, So, requesting them to please review this PR and merge this if they have write access . Otherwise, we have to start thinking of other plans

2022-06-23 05:13 UTC, winfa commented
> > Hi @sharmanikhil04, I was trying to build based on your PR but found errors when run `npm run build` or `npm run build:lib`. Maybe the angular upgrade part may should be covered by nx.
> > Also, not sure if it is possible to keep the dependency as angular 13, and just update the code and keep stateChanges as optional to make this lib support angular 13 and angular 14.
> > @rRaDuCaN @sharmanikhil04 And btw, if @merlosy does not use this account anymore. Do we have any other plans? Do we have any other person can contact with? Or maybe publish this change to anther place?
> 
> @winfa I had upgraded Angular version first to simulate the error and then added stateChanges . Not sure if we should stateChanges as Optional without Angular upgrade. Anyhow, I can see @mcaden and @matcho have also committed to this library, So, requesting them to please review this PR and merge this if they have write access . Otherwise, we have to start thinking of other plans

Sure. Thank you for the reply.

2022-06-24 06:30 UTC, joanroig approved these changes

2022-06-25 12:28 UTC, merlosy commented
Hi all! Sorry for the delay, and thank you for the time and effort in contributing. I have a lot going on atm but I'm not giving up on this.
I'll have a look at this soon!

2022-06-25 19:04 UTC, JeremieLapert commented
> Hi all! Sorry for the delay, and thank you for the time and effort in contributing. I have a lot going on atm but I'm not giving up on this. I'll have a look at this soon!


Can we help you maintain the project?

2022-06-28 02:55 UTC, easyeviction approved these changes

2022-06-28 07:50 UTC, ludonoel1 approved these changes

2022-06-29 06:45 UTC, Soeren86n approved these changes

2022-06-29 16:05 UTC, Leccho approved these changes

2022-06-29 16:05 UTC, Leccho approved these changes

2022-07-02 19:56 UTC, merlosy approved these changes

2022-07-02 19:56 UTC, merged