Migration to Angular 15
merlosy/ngx-material-file-input pull request #135
Opened 2023-01-22 17:16 UTC by p-karbownik

Changed Angular version to 15
Removed unsupported mat-form-field's appearance options

2023-02-20 19:03 UTC, tanoabeleyra commented
Just a heads-up, I see some token you probably didn't mean to push, did you?

2023-03-11 16:01 UTC, WallaceROliveira approved these changes

2023-03-11 16:04 UTC, WallaceROliveira requested changes

2023-03-11 16:04 UTC, WallaceROliveira commented on nx.json
> +        "accessToken": "ZTJhZTAzNGEtOTBhMi00OWFkLTgyMDktNTY2M2Y1ZmE0NTM1fHJlYWQtd3JpdGU="
check need to have token

2023-03-11 18:31 UTC, Den-dp commented on package.json
>      "@angular/cli": "~14.2.0",
should be updated to 15 I guess 🤔

2023-03-20 17:38 UTC, closed without merging